### ISSUE TITLE
Getting cannot read property

### ISSUE THREAD

**Issue by TheFonix** [bluemaex/homebridge-dmxuniverse#2]
Hi there, have been receiving this as soon as i connect my device to home-bridge, and my console now gets spammed with this.. 

```
[2/4/2018, 2:03:43 AM] [DMX] error retrieving state TypeError: Cannot read property 'h' of undefined
    at utils.httpGet.then (/usr/local/lib/node_modules/homebridge-dmxuniverse/devices/stairville-led-par-56.js:104:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Any help would be awesome!

**Comment by bluemaex** [comment]
@TheFonix The DMX library changed to have different offsets in the latest release. I have these errors in my console as well - but haven't had time to look at it. 

I'll try to look into it next week and will report!

**Comment by TheFonix** [comment]
Great thank you! Would be amazing to get this working! 👍 I could revert the dmx library if you could tell me which one you based your application on?

**Comment by TheFonix** [comment]
Any News?

**Comment by bluemaex** [comment]
@TheFonix it turns out that somehow the color-conversion library I use changed their signature.

I updated the source and now this works for me again - Do you want to give the new version a try?

**Comment by TheFonix** [comment]
Yep! That seems to have kicked it back into life, Many thanks! :)
